language: java
jdk:
  - oraclejdk8
script: mvn clean heroku:deploy-war
deploy:
  provider: heroku
  api_key:
    secure: FatPezqBtE4R4zKfj3ljR+nIIxJLVkATfPK7Mmu9ZwiFuJI/5hUbEbFoVdidx2fi8BHRXMvlW22gnxBDQ05NRF6jHEOTe5xV3qVjHxFLSelVhaGDPBU8XteYYTir+0DGWZFrSUZaq4+898mFgbSJhuN0hWkCyKRVJWfzyVSS3KhJpT5fzRdZdZZjRRpexAMepxhebbArsHJy38XKn8sQsj+BAbfkbVkwiKD8IaAwzZKTEFzJLswTAUOXE16caaMsiG5rF9uA2MqW+GPcRZusXeysUWx3j+/0sYmcIqQjo0hCLc/iTkw2afdTazgK9fRg2wnJHZc7rzSDEB2OICGPMZ08pOasEJWrf8T3UlxKJTGV2QJ15tHU10T7jSEOOVFDOx5d8ygjqMY4C8rguhXYAw8q0U7VNoFN0iqguuYaUzXAfoHdmohK72F5NwV8CSCsmTHb/6dubapzU5cCqy+guVBpQJquUfyNd5W+b5MrQnOJ9YJ6s2mt+N0/jO97T/I6B164g0r6eqne0R+pCq3l25kUbezwcDCCthr/NULK+DAiqArwWKnYKl6e5MHieRPtQD2y87745TyCBvhRO1C5icouthhoNyPaDpBJELhB53pL/Mrlz8GCYWjPFu4wU673QqNFZPKETvdDodtNY5T9Ho5TsqSwTb/WCsQ072TZWrg=
  app: ncedu-ecomm
